---

- name: Making swap permanent
  lineinfile:
    dest: /etc/fstab
    line: "{{ swap_file_path }}   none    swap    sw    0   0"

- name: Setting swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"

- name: Setting vfs cache pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swap_vfs_scache_pressure }}"
