---
# @todo: check size and recreate on change

- name: Get stat of swap file
  stat:
    path: "{{ swap_file_path }}"
  register: swap_file_stat

- name: Creating swap file
  command: >
    fallocate -l {{ swap_file_size }} {{ swap_file_path }}
  when: not swap_file_stat.stat.exists

- name: Settings permissions
  file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Making swap
  command: >
    mkswap {{ swap_file_path }}
  when: not swap_file_stat.stat.exists

- name: Enabling swap
  command: >
    swapon {{ swap_file_path }}
  when: not swap_file_stat.stat.exists
